#!/usr/bin/env node
/**
 * AI-GENERATED CODE
 * This file was automatically generated by an AI assistant.
 * DO NOT manually edit this file without understanding the build process.
 * 
 * Build script: Generates config.js from environment variables
 * 
 * Usage:
 * 1. Local development: Set VITE_API_BASE_URL in .env file, then run: node build.js
 * 2. Vercel deployment: Set VITE_API_BASE_URL environment variable in Vercel, auto-builds
 */

const fs = require('fs');
const path = require('path');

// Read environment variable (Vercel automatically provides it, local dev needs .env file)
let apiUrl = process.env.VITE_API_BASE_URL || 'http://localhost:8000';

// If .env file exists locally, try to read from it
const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) {
    const content = fs.readFileSync(envFile, 'utf8');
    // Match VITE_API_BASE_URL=value pattern
    const match = content.match(/VITE_API_BASE_URL=(.+)/);
    if (match) {
        apiUrl = match[1].trim();
    }
}

// Auto-detect Vercel environment and use proxy path
// If running on Vercel and API URL is HTTP (not HTTPS and not relative path), use /api proxy to avoid mixed content
if (process.env.VERCEL && apiUrl.startsWith('http://') && !apiUrl.startsWith('/')) {
    apiUrl = '/api';
    console.log('🔧 Detected Vercel environment with HTTP API, using /api proxy to avoid mixed content');
}

// Generate config.js file content
const configJs = `/**
 * AI-GENERATED CODE
 * This file was automatically generated by build.js from environment variables.
 * DO NOT manually edit this file - it will be overwritten during build.
 */

// Auto-generated configuration file
window.API_CONFIG = { BASE_URL: '${apiUrl}' };
console.log('API Base URL:', window.API_CONFIG.BASE_URL);
`;

// Write config.js to file
fs.writeFileSync(path.join(__dirname, 'config.js'), configJs);
console.log('✅ Configuration generated:', apiUrl);