/**
 * AI-GENERATED CODE
 * This file was automatically generated by build.js from environment variables.
 * DO NOT manually edit this file - it will be overwritten during build.
 */

// Auto-generated configuration file
window.API_CONFIG = { BASE_URL: 'http://localhost:8000' };
console.log('API Base URL:', window.API_CONFIG.BASE_URL);
