/**
 * AI-GENERATED CODE
 * This file was automatically generated by build.js from environment variables.
 * For the current assignment demo, we hard-code the HTTPS backend URL here.
 * If you change the API domain, update the URL below and redeploy.
 */

// Frontend API configuration
window.API_CONFIG = {
  BASE_URL: 'https://api.ata-automatic-team-assembler.com'
};

console.log('API Base URL:', window.API_CONFIG.BASE_URL);
